apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-with-ephemeral-disk
  labels:
    app: nginx4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx4
  serviceName: "nginx"
  template:
    metadata:
      labels:
        app: nginx4
    spec:
      containers:
      - name: nginx4
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        resources:
          limits:
            ephemeral-storage: 1G
      nodeSelector:
        kubernetes.io/hostname: 10.72.206.145
